# Generated by Django 2.2.10 on 2020-06-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('dateStart', models.DateTimeField(auto_now_add=True, verbose_name='Дата старта')),
                ('dateEnd', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questtext', models.TextField()),
                ('questtype', models.CharField(choices=[('TX', 'Ответ текстом'), ('SC', 'Ответ с выбором одного варианта'), ('MC', 'Множественный выбор')], default='TX', max_length=3)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answertext', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('isCorrect', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
        ),
    ]
