# Generated by Django 2.2.10 on 2020-06-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200628_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='userSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='survey.UserSession'),
        ),
    ]
